import re
from typing import Optional
from pydantic import BaseModel, Field, field_validator

# Input model validation schema
class PricingRequest(BaseModel):
    request_id: str = Field(
        ...,
        description="Unique UUID v4 correlation identifier generated by the storefront client"
    )
    product_id: int = Field(
        ..., 
        description="The unique identifier for the Shopify product",
        gt=0
    )
    zip_code: str = Field(
        ..., 
        description="A valid 5-digit US ZIP code",
        examples=["75028", "10001", "90210"]
    )

    @field_validator("request_id")
    @classmethod
    def validate_uuid_format(cls, value: str) -> str:
        # Validates standard UUID structure
        uuid_regex = r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
        if not re.match(uuid_regex, value):
            raise ValueError("request_id must be a valid UUID v4 string")
        return value

    @field_validator("zip_code")
    @classmethod
    def validate_us_zip(cls, value: str) -> str:
        # Strict pattern matching to ensure it's precisely 5 digits
        if not re.match(r"^\d{5}$", value):
            raise ValueError("ZIP code must be a valid 5-digit US ZIP code (e.g., 75028)")
        return value

# Output response schema representation
class PricingResponse(BaseModel):
    success: bool = Field(..., description="Indicates if the API executed successfully")
    zip_code: str = Field(..., description="The zip code queried")
    product_id: int = Field(..., description="The Shopify product ID evaluated")
    price: Optional[float] = Field(None, description="The custom price calculated, or null if fallback to default")
    formatted_price: Optional[str] = Field(None, description="The currency-formatted custom price, or null if fallback")
    is_custom: bool = Field(..., description="True if a custom rule applies, False if falling back to storefront default")
    message: str = Field(..., description="Human-readable execution status message")
